#ifndef CONFIG_H_INCLUDED
#define CONFIG_H_INCLUDED
#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 600
#define ASTEROID_MIN_SPEED 10
#define ASTEROID_MAX_SPEED 30
#define MISSILE_SPEED 10
#define MISSILE_RANGE 600
#define MISSILE_LIFE_TIME (MISSILE_RANGE / MISSILE_SPEED)
#define MISSILE_RADIUS 2
#define FIRE_DELAY 10
#include "raylib.h"
#endif // CONFIG_H_INCLUDED
