#ifndef CONFIG_H_INCLUDED
#include "raylib.h"
#define CONFIG_H_INCLUDED
#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 600
#define ASTEROID_MIN_SPEED 10
#define ASTEROID_MAX_SPEED 30
#define MISSILE_LIFE_TIME 120
#define MISSILE_SPEED 3
#define MISSILE_RADIUS 2

#endif // CONFIG_H_INCLUDED
